# Generated by Django 3.1.7 on 2021-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='shield',
            field=models.BooleanField(default=False),
        ),
    ]
