# Generated by Django 3.1.7 on 2021-03-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceset',
            options={'permissions': {('sourcesets.can_edit', 'Can Edit')}},
        ),
    ]
