# Generated by Django 3.1.7 on 2021-03-19 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characterSheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saga',
            name='members',
            field=models.ManyToManyField(related_name='Member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saga',
            name='storyGuide',
            field=models.ManyToManyField(related_name='Storyguide', to=settings.AUTH_USER_MODEL),
        ),
    ]
