# Generated by Django 3.1.7 on 2021-03-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0002_auto_20210327_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceset',
            options={'permissions': {('source_can_edit', 'Can Edit')}},
        ),
    ]
