# Generated by Django 3.1.7 on 2021-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0002_weapon_shield'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='freeHand',
            field=models.BooleanField(default=False, verbose_name='Can hold other objects in same hand'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='twoHanded',
            field=models.BooleanField(default=False, verbose_name='Two-handed'),
        ),
    ]
