# Generated by Django 3.1.7 on 2021-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0002_auto_20210318_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('g', 'grog'), ('c', 'companion'), ('m', 'magus'), ('n', 'npc')], default='n', max_length=1, verbose_name='Character Type:'),
        ),
    ]
