# Generated by Django 3.1.7 on 2021-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0003_auto_20210408_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='atk',
            field=models.IntegerField(default=0, verbose_name='Attack'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dam',
            field=models.IntegerField(default=0, verbose_name='Damage'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dfn',
            field=models.IntegerField(default=0, verbose_name='Defence'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='init',
            field=models.IntegerField(default=0, verbose_name='Initiative'),
        ),
    ]
