# Generated by Django 3.1.7 on 2021-03-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0003_auto_20210327_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceset',
            name='sagas',
        ),
        migrations.AddField(
            model_name='saga',
            name='sourceSets',
            field=models.ManyToManyField(blank=True, to='characterSheets.SourceSet'),
        ),
    ]
