# Generated by Django 3.1.7 on 2021-04-10 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0004_auto_20210408_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('domusMagna', models.CharField(max_length=200)),
                ('primus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('form', models.CharField(choices=[('cr', 'creo'), ('in', 'intellego'), ('mu', 'muto'), ('pe', 'perdo'), ('re', 'rego')], max_length=2)),
                ('technique', models.CharField(choices=[('an', 'animal'), ('aq', 'aquam'), ('au', 'auram'), ('co', 'corpus'), ('he', 'herbam'), ('ig', 'ignem'), ('im', 'imaginem'), ('me', 'mentem'), ('te', 'terram'), ('vi', 'vim')], max_length=2)),
                ('level', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterSheets.sourceset')),
            ],
        ),
        migrations.CreateModel(
            name='SpellGuideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('form', models.CharField(choices=[('cr', 'creo'), ('in', 'intellego'), ('mu', 'muto'), ('pe', 'perdo'), ('re', 'rego')], max_length=2)),
                ('technique', models.CharField(choices=[('an', 'animal'), ('aq', 'aquam'), ('au', 'auram'), ('co', 'corpus'), ('he', 'herbam'), ('ig', 'ignem'), ('im', 'imaginem'), ('me', 'mentem'), ('te', 'terram'), ('vi', 'vim')], max_length=2)),
                ('general', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'unique_together': {('form', 'technique')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='covApprentice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Covenant of Apprenticeship'),
        ),
        migrations.AddField(
            model_name='character',
            name='parens',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='sigil',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Wizard's Sigil"),
        ),
        migrations.CreateModel(
            name='SpellInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('mastery', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('referenceSpell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterSheets.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellGuidelineExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterSheets.spellguideline')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterSheets.sourceset')),
            ],
        ),
        migrations.CreateModel(
            name='spellCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('r', 'range'), ('d', 'duration'), ('t', 'target')], max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('level', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterSheets.sourceset')),
            ],
        ),
        migrations.AddField(
            model_name='spell',
            name='spellDuration',
            field=models.ForeignKey(limit_choices_to={'type': 'd'}, on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='characterSheets.spellcharacteristic'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spellRange',
            field=models.ForeignKey(limit_choices_to={'type': 'r'}, on_delete=django.db.models.deletion.CASCADE, related_name='range', to='characterSheets.spellcharacteristic'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spellTarget',
            field=models.ForeignKey(limit_choices_to={'type': 't'}, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='characterSheets.spellcharacteristic'),
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cr', 'creo'), ('in', 'intellego'), ('mu', 'muto'), ('pe', 'perdo'), ('re', 'rego'), ('an', 'animal'), ('aq', 'aquam'), ('au', 'auram'), ('co', 'corpus'), ('he', 'herbam'), ('ig', 'ignem'), ('im', 'imaginem'), ('me', 'mentem'), ('te', 'terram'), ('vi', 'vim')], max_length=2)),
                ('score', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterSheets.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characterSheets.house'),
        ),
    ]
