# Generated by Django 3.1.7 on 2021-04-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0005_auto_20210409_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellguideline',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
