# Generated by Django 3.1.7 on 2021-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0007_auto_20210411_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
    ]
