# Generated by Django 3.1.7 on 2021-04-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0008_spell_ritual'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellinstance',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='characterSheets.character'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='art',
            unique_together={('name', 'character')},
        ),
    ]
