# Generated by Django 3.1.7 on 2021-04-13 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characterSheets', '0009_auto_20210412_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceset',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spellinstance',
            name='sigil',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saga',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
