# Generated by Django 3.1.7 on 2021-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterSheets', '0010_auto_20210412_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellinstance',
            name='type',
            field=models.CharField(choices=[('d', 'draft'), ('s', 'spontaneous'), ('f', 'formulaic')], default='d', max_length=1),
        ),
    ]
