# Generated by Django 3.1.7 on 2021-04-13 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characterSheets', '0011_spellinstance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saga',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
